<?php

namespace App\Helpers;

class CountryHelper
{
    public static $countries = [
        'XX' => [
            'iso' => 'XX',
            'name' => 'Anonymous',
            'iso3' => 'XXX',
            'prefix' => '',
            'defaultLang' => 'en',
            'nationality' => 'Mysterious',
            'currency' => 'EUR',
        ],
        'AF' => [
            'iso' => 'AF',
            'name' => 'Afghanistan',
            'iso3' => 'AFG',
            'prefix' => '93',
            'defaultLang' => 'ar',
            'nationality' => 'Afghan',
            'currency' => 'USD',
        ],
        'AL' => [
            'iso' => 'AL',
            'name' => 'Albania',
            'iso3' => 'ALB',
            'prefix' => '355',
            'defaultLang' => 'en',
            'nationality' => 'Albanian',
            'currency' => 'USD',
        ],
        'DZ' => [
            'iso' => 'DZ',
            'name' => 'Algeria',
            'iso3' => 'DZA',
            'prefix' => '213',
            'defaultLang' => 'ar',
            'nationality' => 'Algerian',
            'currency' => 'USD',
        ],
        'AS' => [
            'iso' => 'AS',
            'name' => 'American Samoa',
            'iso3' => 'ASM',
            'prefix' => '1684',
            'defaultLang' => 'en',
            'nationality' => 'American Samoan',
            'currency' => 'USD',
        ],
        'AD' => [
            'iso' => 'AD',
            'name' => 'Andorra',
            'iso3' => 'AND',
            'prefix' => '376',
            'defaultLang' => 'en',
            'nationality' => 'Andorran',
            'currency' => 'USD',
        ],
        'AO' => [
            'iso' => 'AO',
            'name' => 'Angola',
            'iso3' => 'AGO',
            'prefix' => '244',
            'defaultLang' => 'pt-br',
            'nationality' => 'Angolan',
            'currency' => 'USD',
        ],
        'AI' => [
            'iso' => 'AI',
            'name' => 'Anguilla',
            'iso3' => 'AIA',
            'prefix' => '1264',
            'defaultLang' => 'en',
            'nationality' => 'Anguilla',
            'currency' => 'USD',
        ],
        'AQ' => [
            'iso' => 'AQ',
            'name' => 'Antarctica',
            'iso3' => '',
            'prefix' => '672',
            'defaultLang' => 'en',
            'nationality' => 'Antarctican',
            'currency' => 'USD',
        ],
        'AG' => [
            'iso' => 'AG',
            'name' => 'Antigua and Barbuda',
            'iso3' => 'ATG',
            'prefix' => '1268',
            'defaultLang' => 'en',
            'nationality' => 'Antiguan/Barbudan',
            'currency' => 'USD',
        ],
        'AR' => [
            'iso' => 'AR',
            'name' => 'Argentina',
            'iso3' => 'ARG',
            'prefix' => '54',
            'defaultLang' => 'es',
            'nationality' => 'Argentine',
            'currency' => 'USD',
        ],
        'AM' => [
            'iso' => 'AM',
            'name' => 'Armenia',
            'iso3' => 'ARM',
            'prefix' => '374',
            'defaultLang' => 'en',
            'nationality' => 'Armenian',
            'currency' => 'USD',
        ],
        'AW' => [
            'iso' => 'AW',
            'name' => 'Aruba',
            'iso3' => 'ABW',
            'prefix' => '297',
            'defaultLang' => 'en',
            'nationality' => 'Aruban',
            'currency' => 'USD',
        ],
        'AU' => [
            'iso' => 'AU',
            'name' => 'Australia',
            'iso3' => 'AUS',
            'prefix' => '61',
            'defaultLang' => 'en',
            'nationality' => 'Australian',
            'currency' => 'USD',
        ],
        'AT' => [
            'iso' => 'AT',
            'name' => 'Austria',
            'iso3' => 'AUT',
            'prefix' => '43',
            'defaultLang' => 'de',
            'nationality' => 'Austrian',
            'currency' => 'EUR',
        ],
        'AZ' => [
            'iso' => 'AZ',
            'name' => 'Azerbaijan',
            'iso3' => 'AZE',
            'prefix' => '994',
            'defaultLang' => 'en',
            'nationality' => 'Azerbaijani',
            'currency' => 'USD',
        ],
        'BS' => [
            'iso' => 'BS',
            'name' => 'Bahamas',
            'iso3' => 'BHS',
            'prefix' => '1242',
            'defaultLang' => 'en',
            'nationality' => 'Bahamian',
            'currency' => 'USD',
        ],
        'BH' => [
            'iso' => 'BH',
            'name' => 'Bahrain',
            'iso3' => 'BHR',
            'prefix' => '973',
            'defaultLang' => 'ar',
            'nationality' => 'Bahraini',
            'currency' => 'USD',
        ],
        'BD' => [
            'iso' => 'BD',
            'name' => 'Bangladesh',
            'iso3' => 'BGD',
            'prefix' => '880',
            'defaultLang' => 'en',
            'nationality' => 'Bangladeshi',
            'currency' => 'USD',
        ],
        'BB' => [
            'iso' => 'BB',
            'name' => 'Barbados',
            'iso3' => 'BRB',
            'prefix' => '1246',
            'defaultLang' => 'en',
            'nationality' => 'Barbadian',
            'currency' => 'USD',
        ],
        'BY' => [
            'iso' => 'BY',
            'name' => 'Belarus',
            'iso3' => 'BLR',
            'prefix' => '375',
            'defaultLang' => 'ru',
            'nationality' => 'Belarusian',
            'currency' => 'USD',
        ],
        'BE' => [
            'iso' => 'BE',
            'name' => 'Belgium',
            'iso3' => 'BEL',
            'prefix' => '32',
            'defaultLang' => 'fr',
            'nationality' => 'Belgian',
            'currency' => 'EUR',
        ],
        'BZ' => [
            'iso' => 'BZ',
            'name' => 'Belize',
            'iso3' => 'BLZ',
            'prefix' => '501',
            'defaultLang' => 'en',
            'nationality' => 'Belizean',
            'currency' => 'USD',
        ],
        'BJ' => [
            'iso' => 'BJ',
            'name' => 'Benin',
            'iso3' => 'BEN',
            'prefix' => '229',
            'defaultLang' => 'fr',
            'nationality' => 'Beninese',
            'currency' => 'USD',
        ],
        'BM' => [
            'iso' => 'BM',
            'name' => 'Bermuda',
            'iso3' => 'BMU',
            'prefix' => '1441',
            'defaultLang' => 'en',
            'nationality' => 'Bermudian',
            'currency' => 'USD',
        ],
        'BT' => [
            'iso' => 'BT',
            'name' => 'Bhutan',
            'iso3' => 'BTN',
            'prefix' => '975',
            'defaultLang' => 'en',
            'nationality' => 'Bhutanese',
            'currency' => 'USD',
        ],
        'BO' => [
            'iso' => 'BO',
            'name' => 'Bolivia',
            'iso3' => 'BOL',
            'prefix' => '591',
            'defaultLang' => 'es',
            'nationality' => 'Bolivian',
            'currency' => 'USD',
        ],
        'BA' => [
            'iso' => 'BA',
            'name' => 'Bosnia and Herzegovina',
            'iso3' => 'BIH',
            'prefix' => '387',
            'defaultLang' => 'ru',
            'nationality' => 'Bosnian/Herzegovinian',
            'currency' => 'USD',
        ],
        'BW' => [
            'iso' => 'BW',
            'name' => 'Botswana',
            'iso3' => 'BWA',
            'prefix' => '267',
            'defaultLang' => 'en',
            'nationality' => 'Botswana/Motswana',
            'currency' => 'USD',
        ],
        'BV' => [
            'iso' => 'BV',
            'name' => 'Bouvet Island',
            'iso3' => null,
            'prefix' => null,
            'defaultLang' => 'en',
            'nationality' => 'Bouvet Island',
            'currency' => 'USD',
        ],
        'BR' => [
            'iso' => 'BR',
            'name' => 'Brazil',
            'iso3' => 'BRA',
            'prefix' => '55',
            'defaultLang' => 'pt-br',
            'nationality' => 'Brazilian',
            'currency' => 'USD',
        ],
        'IO' => [
            'iso' => 'IO',
            'name' => 'British Indian Ocean Territory',
            'iso3' => null,
            'prefix' => '246',
            'defaultLang' => 'en',
            'nationality' => 'British Indian Ocean Territory',
            'currency' => 'USD',
        ],
        'BN' => [
            'iso' => 'BN',
            'name' => 'Brunei Darussalam',
            'iso3' => 'BRN',
            'prefix' => '673',
            'defaultLang' => 'ar',
            'nationality' => 'Bruneian',
            'currency' => 'USD',
        ],
        'BG' => [
            'iso' => 'BG',
            'name' => 'Bulgaria',
            'iso3' => 'BGR',
            'prefix' => '359',
            'defaultLang' => 'en',
            'nationality' => 'Bulgarian',
            'currency' => 'USD',
        ],
        'BF' => [
            'iso' => 'BF',
            'name' => 'Burkina Faso',
            'iso3' => 'BFA',
            'prefix' => '226',
            'defaultLang' => 'es',
            'nationality' => 'Burkinabe',
            'currency' => 'USD',
        ],
        'BI' => [
            'iso' => 'BI',
            'name' => 'Burundi',
            'iso3' => 'BDI',
            'prefix' => '257',
            'defaultLang' => 'en',
            'nationality' => 'Burundian',
            'currency' => 'USD',
        ],
        'KH' => [
            'iso' => 'KH',
            'name' => 'Cambodia',
            'iso3' => 'KHM',
            'prefix' => '855',
            'defaultLang' => 'en',
            'nationality' => 'Cambodian',
            'currency' => 'USD',
        ],
        'CM' => [
            'iso' => 'CM',
            'name' => 'Cameroon',
            'iso3' => 'CMR',
            'prefix' => '237',
            'defaultLang' => 'en',
            'nationality' => 'Cameroonian',
            'currency' => 'USD',
        ],
        'CA' => [
            'iso' => 'CA',
            'name' => 'Canada',
            'iso3' => 'CAN',
            'prefix' => '1',
            'defaultLang' => 'en',
            'nationality' => 'Canadian',
            'currency' => 'USD',
        ],
        'CV' => [
            'iso' => 'CV',
            'name' => 'Cape Verde',
            'iso3' => 'CPV',
            'prefix' => '238',
            'defaultLang' => 'pt-br',
            'nationality' => 'Cape Verdian',
            'currency' => 'USD',
        ],
        'KY' => [
            'iso' => 'KY',
            'name' => 'Cayman Islands',
            'iso3' => 'CYM',
            'prefix' => '1345',
            'defaultLang' => 'en',
            'nationality' => 'Cayman Islander',
            'currency' => 'USD',
        ],
        'CF' => [
            'iso' => 'CF',
            'name' => 'Central African Republic',
            'iso3' => 'CAF',
            'prefix' => '236',
            'defaultLang' => 'en',
            'nationality' => 'Central African',
            'currency' => 'USD',
        ],
        'TD' => [
            'iso' => 'TD',
            'name' => 'Chad',
            'iso3' => 'TCD',
            'prefix' => '235',
            'defaultLang' => 'en',
            'nationality' => 'Chadian',
            'currency' => 'USD',
        ],
        'CL' => [
            'iso' => 'CL',
            'name' => 'Chile',
            'iso3' => 'CHL',
            'prefix' => '56',
            'defaultLang' => 'es',
            'nationality' => 'Chilean',
            'currency' => 'USD',
        ],
        'CN' => [
            'iso' => 'CN',
            'name' => 'China',
            'iso3' => 'CHN',
            'prefix' => '86',
            'defaultLang' => 'en',
            'nationality' => 'Chinese',
            'currency' => 'USD',
        ],
        'CX' => [
            'iso' => 'CX',
            'name' => 'Christmas Island',
            'iso3' => null,
            'prefix' => '61',
            'defaultLang' => 'en',
            'nationality' => 'Christmas Islander',
            'currency' => 'USD',
        ],
        'CC' => [
            'iso' => 'CC',
            'name' => 'Cocos (Keeling) Islands',
            'iso3' => '',
            'prefix' => '61',
            'defaultLang' => 'en',
            'nationality' => 'Cocos (Keeling) Islander',
            'currency' => 'USD',
        ],
        'CO' => [
            'iso' => 'CO',
            'name' => 'Colombia',
            'iso3' => 'COL',
            'prefix' => '57',
            'defaultLang' => 'es',
            'nationality' => 'Colombian',
            'currency' => 'USD',
        ],
        'KM' => [
            'iso' => 'KM',
            'name' => 'Comoros',
            'iso3' => 'COM',
            'prefix' => '269',
            'defaultLang' => 'en',
            'nationality' => 'Comoran',
            'currency' => 'USD',
        ],
        'CG' => [
            'iso' => 'CG',
            'name' => 'Congo',
            'iso3' => 'COG',
            'prefix' => '242',
            'defaultLang' => 'en',
            'nationality' => 'Congolese',
            'currency' => 'USD',
        ],
        'CD' => [
            'iso' => 'CD',
            'name' => 'Congo, the Democratic Republic of the',
            'iso3' => 'COD',
            'prefix' => '243',
            'defaultLang' => 'en',
            'nationality' => 'Congolese',
            'currency' => 'USD',
        ],
        'CK' => [
            'iso' => 'CK',
            'name' => 'Cook Islands',
            'iso3' => 'COK',
            'prefix' => '682',
            'defaultLang' => 'en',
            'nationality' => 'Cook Islander',
            'currency' => 'USD',
        ],
        'CR' => [
            'iso' => 'CR',
            'name' => 'Costa Rica',
            'iso3' => 'CRI',
            'prefix' => '506',
            'defaultLang' => 'es',
            'nationality' => 'Costa Rican',
            'currency' => 'USD',
        ],
        'CI' => [
            'iso' => 'CI',
            'name' => 'Cote D\'Ivoire',
            'iso3' => 'CIV',
            'prefix' => '225',
            'defaultLang' => 'fr',
            'nationality' => 'Ivorian',
            'currency' => 'USD',
        ],
        'HR' => [
            'iso' => 'HR',
            'name' => 'Croatia',
            'iso3' => 'HRV',
            'prefix' => '385',
            'defaultLang' => 'en',
            'nationality' => 'Croatian',
            'currency' => 'USD',
        ],
        'CU' => [
            'iso' => 'CU',
            'name' => 'Cuba',
            'iso3' => 'CUB',
            'prefix' => '53',
            'defaultLang' => 'es',
            'nationality' => 'Cuban',
            'currency' => 'USD',
        ],
        'CY' => [
            'iso' => 'CY',
            'name' => 'Cyprus',
            'iso3' => 'CYP',
            'prefix' => '357',
            'defaultLang' => 'en',
            'nationality' => 'Cypriot',
            'currency' => 'EUR',
        ],
        'CZ' => [
            'iso' => 'CZ',
            'name' => 'Czech Republic',
            'iso3' => 'CZE',
            'prefix' => '420',
            'defaultLang' => 'en',
            'nationality' => 'Czech',
            'currency' => 'USD',
        ],
        'DK' => [
            'iso' => 'DK',
            'name' => 'Denmark',
            'iso3' => 'DNK',
            'prefix' => '45',
            'defaultLang' => 'en',
            'nationality' => 'Danish',
            'currency' => 'USD',
        ],
        'DJ' => [
            'iso' => 'DJ',
            'name' => 'Djibouti',
            'iso3' => 'DJI',
            'prefix' => '253',
            'defaultLang' => 'en',
            'nationality' => 'Djiboutian',
            'currency' => 'USD',
        ],
        'DM' => [
            'iso' => 'DM',
            'name' => 'Dominica',
            'iso3' => 'DMA',
            'prefix' => '1767',
            'defaultLang' => 'es',
            'nationality' => 'Dominican',
            'currency' => 'USD',
        ],
        'DO' => [
            'iso' => 'DO',
            'name' => 'Dominican Republic',
            'iso3' => 'DOM',
            'prefix' => '1809',
            'defaultLang' => 'es',
            'nationality' => 'Dominican',
            'currency' => 'USD',
        ],
        'EC' => [
            'iso' => 'EC',
            'name' => 'Ecuador',
            'iso3' => 'ECU',
            'prefix' => '593',
            'defaultLang' => 'es',
            'nationality' => 'Ecuadorian',
            'currency' => 'USD',
        ],
        'EG' => [
            'iso' => 'EG',
            'name' => 'Egypt',
            'iso3' => 'EGY',
            'prefix' => '20',
            'defaultLang' => 'ar',
            'nationality' => 'Egyptian',
            'currency' => 'USD',
        ],
        'SV' => [
            'iso' => 'SV',
            'name' => 'El Salvador',
            'iso3' => 'SLV',
            'prefix' => '503',
            'defaultLang' => 'es',
            'nationality' => 'Salvadorian',
            'currency' => 'USD',
        ],
        'GQ' => [
            'iso' => 'GQ',
            'name' => 'Equatorial Guinea',
            'iso3' => 'GNQ',
            'prefix' => '240',
            'defaultLang' => 'en',
            'nationality' => 'Equatoguinean',
            'currency' => 'USD',
        ],
        'ER' => [
            'iso' => 'ER',
            'name' => 'Eritrea',
            'iso3' => 'ERI',
            'prefix' => '291',
            'defaultLang' => 'en',
            'nationality' => 'Eritrean',
            'currency' => 'USD',
        ],
        'EE' => [
            'iso' => 'EE',
            'name' => 'Estonia',
            'iso3' => 'EST',
            'prefix' => '372',
            'defaultLang' => 'en',
            'nationality' => 'Estonian',
            'currency' => 'EUR',
        ],
        'ET' => [
            'iso' => 'ET',
            'name' => 'Ethiopia',
            'iso3' => 'ETH',
            'prefix' => '251',
            'defaultLang' => 'en',
            'nationality' => 'Ethiopian',
            'currency' => 'USD',
        ],
        'FK' => [
            'iso' => 'FK',
            'name' => 'Falkland Islands (Malvinas)',
            'iso3' => 'FLK',
            'prefix' => '500',
            'defaultLang' => 'en',
            'nationality' => 'Falkland Islander (Malvinas)',
            'currency' => 'USD',
        ],
        'FO' => [
            'iso' => 'FO',
            'name' => 'Faroe Islands',
            'iso3' => 'FRO',
            'prefix' => '298',
            'defaultLang' => 'en',
            'nationality' => 'Faroe Islander',
            'currency' => 'USD',
        ],
        'FJ' => [
            'iso' => 'FJ',
            'name' => 'Fiji',
            'iso3' => 'FJI',
            'prefix' => '679',
            'defaultLang' => 'en',
            'nationality' => 'Fijian',
            'currency' => 'USD',
        ],
        'FI' => [
            'iso' => 'FI',
            'name' => 'Finland',
            'iso3' => 'FIN',
            'prefix' => '358',
            'defaultLang' => 'en',
            'nationality' => 'Finnish',
            'currency' => 'EUR',
        ],
        'FR' => [
            'iso' => 'FR',
            'name' => 'France',
            'iso3' => 'FRA',
            'prefix' => '33',
            'defaultLang' => 'fr',
            'nationality' => 'French',
            'currency' => 'EUR',
        ],
        'GF' => [
            'iso' => 'GF',
            'name' => 'French Guiana',
            'iso3' => 'GUF',
            'prefix' => '',
            'defaultLang' => 'fr',
            'nationality' => 'French Guianese',
            'currency' => 'USD',
        ],
        'PF' => [
            'iso' => 'PF',
            'name' => 'French Polynesia',
            'iso3' => 'PYF',
            'prefix' => '689',
            'defaultLang' => 'fr',
            'nationality' => 'French Polynesian',
            'currency' => 'USD',
        ],
        'TF' => [
            'iso' => 'TF',
            'name' => 'French Southern Territories',
            'iso3' => null,
            'prefix' => null,
            'defaultLang' => 'fr',
            'nationality' => 'French Southern Territories',
            'currency' => 'USD',
        ],
        'GA' => [
            'iso' => 'GA',
            'name' => 'Gabon',
            'iso3' => 'GAB',
            'prefix' => '241',
            'defaultLang' => 'en',
            'nationality' => 'Gabonese',
            'currency' => 'USD',
        ],
        'GM' => [
            'iso' => 'GM',
            'name' => 'Gambia',
            'iso3' => 'GMB',
            'prefix' => '220',
            'defaultLang' => 'en',
            'nationality' => 'Gambian',
            'currency' => 'USD',
        ],
        'GE' => [
            'iso' => 'GE',
            'name' => 'Georgia',
            'iso3' => 'GEO',
            'prefix' => '995',
            'defaultLang' => 'ru',
            'nationality' => 'Georgian',
            'currency' => 'USD',
        ],
        'DE' => [
            'iso' => 'DE',
            'name' => 'Germany',
            'iso3' => 'DEU',
            'prefix' => '49',
            'defaultLang' => 'de',
            'nationality' => 'German',
            'currency' => 'EUR',
        ],
        'GH' => [
            'iso' => 'GH',
            'name' => 'Ghana',
            'iso3' => 'GHA',
            'prefix' => '233',
            'defaultLang' => 'en',
            'nationality' => 'Ghanaian',
            'currency' => 'USD',
        ],
        'GI' => [
            'iso' => 'GI',
            'name' => 'Gibraltar',
            'iso3' => 'GIB',
            'prefix' => '350',
            'defaultLang' => 'en',
            'nationality' => 'Gibraltarian',
            'currency' => 'USD',
        ],
        'GR' => [
            'iso' => 'GR',
            'name' => 'Greece',
            'iso3' => 'GRC',
            'prefix' => '30',
            'defaultLang' => 'en',
            'nationality' => 'Greek',
            'currency' => 'EUR',
        ],
        'GL' => [
            'iso' => 'GL',
            'name' => 'Greenland',
            'iso3' => 'GRL',
            'prefix' => '299',
            'defaultLang' => 'en',
            'nationality' => 'Greenlander',
            'currency' => 'USD',
        ],
        'GD' => [
            'iso' => 'GD',
            'name' => 'Grenada',
            'iso3' => 'GRD',
            'prefix' => '1473',
            'defaultLang' => 'en',
            'nationality' => 'Grenadian',
            'currency' => 'USD',
        ],
        'GP' => [
            'iso' => 'GP',
            'name' => 'Guadeloupe',
            'iso3' => 'GLP',
            'prefix' => '590',
            'defaultLang' => 'es',
            'nationality' => 'Guatemalan',
            'currency' => 'USD',
        ],
        'GU' => [
            'iso' => 'GU',
            'name' => 'Guam',
            'iso3' => 'GUM',
            'prefix' => '1671',
            'defaultLang' => 'en',
            'nationality' => 'Guamanian',
            'currency' => 'USD',
        ],
        'GT' => [
            'iso' => 'GT',
            'name' => 'Guatemala',
            'iso3' => 'GTM',
            'prefix' => '502',
            'defaultLang' => 'es',
            'nationality' => 'Guatemalan',
            'currency' => 'USD',
        ],
        'GN' => [
            'iso' => 'GN',
            'name' => 'Guinea',
            'iso3' => 'GIN',
            'prefix' => '224',
            'defaultLang' => 'en',
            'nationality' => 'Guinean',
            'currency' => 'USD',
        ],
        'GW' => [
            'iso' => 'GW',
            'name' => 'Guinea-Bissau',
            'iso3' => 'GNB',
            'prefix' => '245',
            'defaultLang' => 'en',
            'nationality' => 'Guinea-Bissauan',
            'currency' => 'USD',
        ],
        'GY' => [
            'iso' => 'GY',
            'name' => 'Guyana',
            'iso3' => 'GUY',
            'prefix' => '592',
            'defaultLang' => 'en',
            'nationality' => 'Guyanese',
            'currency' => 'USD',
        ],
        'HT' => [
            'iso' => 'HT',
            'name' => 'Haiti',
            'iso3' => 'HTI',
            'prefix' => '509',
            'defaultLang' => 'fr',
            'nationality' => 'Haitian',
            'currency' => 'USD',
        ],
        'HM' => [
            'iso' => 'HM',
            'name' => 'Heard Island and Mcdonald Islands',
            'iso3' => null,
            'prefix' => null,
            'defaultLang' => 'en',
            'nationality' => 'Heard Island and Mcdonald Islands',
            'currency' => 'USD',
        ],
        'VA' => [
            'iso' => 'VA',
            'name' => 'Holy See (Vatican City State)',
            'iso3' => 'VAT',
            'prefix' => '379',
            'defaultLang' => 'en',
            'nationality' => 'Holy See (Vatican City State)',
            'currency' => 'USD',
        ],
        'HN' => [
            'iso' => 'HN',
            'name' => 'Honduras',
            'iso3' => 'HND',
            'prefix' => '504',
            'defaultLang' => 'es',
            'nationality' => 'Honduran',
            'currency' => 'USD',
        ],
        'HK' => [
            'iso' => 'HK',
            'name' => 'Hong Kong',
            'iso3' => 'HKG',
            'prefix' => '852',
            'defaultLang' => 'en',
            'nationality' => 'Chinese',
            'currency' => 'USD',
        ],
        'HU' => [
            'iso' => 'HU',
            'name' => 'Hungary',
            'iso3' => 'HUN',
            'prefix' => '36',
            'defaultLang' => 'en',
            'nationality' => 'Hungarian/Magyar',
            'currency' => 'USD',
        ],
        'IS' => [
            'iso' => 'IS',
            'name' => 'Iceland',
            'iso3' => 'ISL',
            'prefix' => '354',
            'defaultLang' => 'en',
            'nationality' => 'Icelander',
            'currency' => 'USD',
        ],
        'IN' => [
            'iso' => 'IN',
            'name' => 'India',
            'iso3' => 'IND',
            'prefix' => '91',
            'defaultLang' => 'en',
            'nationality' => 'Indian',
            'currency' => 'USD',
        ],
        'ID' => [
            'iso' => 'ID',
            'name' => 'Indonesia',
            'iso3' => 'IDN',
            'prefix' => '62',
            'defaultLang' => 'en',
            'nationality' => 'Indonesian',
            'currency' => 'USD',
        ],
        'IR' => [
            'iso' => 'IR',
            'name' => 'Iran, Islamic Republic of',
            'iso3' => 'IRN',
            'prefix' => '98',
            'defaultLang' => 'ar',
            'nationality' => 'Iranian',
            'currency' => 'USD',
        ],
        'IQ' => [
            'iso' => 'IQ',
            'name' => 'Iraq',
            'iso3' => 'IRQ',
            'prefix' => '964',
            'defaultLang' => 'ar',
            'nationality' => 'Iraqi',
            'currency' => 'USD',
        ],
        'IE' => [
            'iso' => 'IE',
            'name' => 'Ireland',
            'iso3' => 'IRL',
            'prefix' => '353',
            'defaultLang' => 'en',
            'nationality' => 'Irish',
            'currency' => 'EUR',
        ],
        'IL' => [
            'iso' => 'IL',
            'name' => 'Israel',
            'iso3' => 'ISR',
            'prefix' => '972',
            'defaultLang' => 'en',
            'nationality' => 'Israeli',
            'currency' => 'USD',
        ],
        'IT' => [
            'iso' => 'IT',
            'name' => 'Italy',
            'iso3' => 'ITA',
            'prefix' => '39',
            'defaultLang' => 'it',
            'nationality' => 'Italian',
            'currency' => 'EUR',
        ],
        'JM' => [
            'iso' => 'JM',
            'name' => 'Jamaica',
            'iso3' => 'JAM',
            'prefix' => '1876',
            'defaultLang' => 'en',
            'nationality' => 'Jamaican',
            'currency' => 'USD',
        ],
        'JP' => [
            'iso' => 'JP',
            'name' => 'Japan',
            'iso3' => 'JPN',
            'prefix' => '81',
            'defaultLang' => 'en',
            'nationality' => 'Japanese',
            'currency' => 'USD',
        ],
        'JO' => [
            'iso' => 'JO',
            'name' => 'Jordan',
            'iso3' => 'JOR',
            'prefix' => '962',
            'defaultLang' => 'ar',
            'nationality' => 'Jordanian',
            'currency' => 'USD',
        ],
        'KZ' => [
            'iso' => 'KZ',
            'name' => 'Kazakhstan',
            'iso3' => 'KAZ',
            'prefix' => '7',
            'defaultLang' => 'ru',
            'nationality' => 'Kazakhstani',
            'currency' => 'USD',
        ],
        'KE' => [
            'iso' => 'KE',
            'name' => 'Kenya',
            'iso3' => 'KEN',
            'prefix' => '254',
            'defaultLang' => 'en',
            'nationality' => 'Kenyan',
            'currency' => 'USD',
        ],
        'KI' => [
            'iso' => 'KI',
            'name' => 'Kiribati',
            'iso3' => 'KIR',
            'prefix' => '686',
            'defaultLang' => 'en',
            'nationality' => 'Kiribati',
            'currency' => 'USD',
        ],
        'KP' => [
            'iso' => 'KP',
            'name' => 'Korea, Democratic People\'s Republic of',
            'iso3' => 'PRK',
            'prefix' => '850',
            'defaultLang' => 'en',
            'nationality' => 'North Korean',
            'currency' => 'USD',
        ],
        'KR' => [
            'iso' => 'KR',
            'name' => 'Korea, Republic of',
            'iso3' => 'KOR',
            'prefix' => '82',
            'defaultLang' => 'en',
            'nationality' => 'South Korean',
            'currency' => 'USD',
        ],
        'KW' => [
            'iso' => 'KW',
            'name' => 'Kuwait',
            'iso3' => 'KWT',
            'prefix' => '965',
            'defaultLang' => 'ar',
            'nationality' => 'Kuwaiti',
            'currency' => 'USD',
        ],
        'KG' => [
            'iso' => 'KG',
            'name' => 'Kyrgyzstan',
            'iso3' => 'KGZ',
            'prefix' => '996',
            'defaultLang' => 'ru',
            'nationality' => 'Kyrgyz',
            'currency' => 'USD',
        ],
        'LA' => [
            'iso' => 'LA',
            'name' => 'Lao People\'s Democratic Republic',
            'iso3' => 'LAO',
            'prefix' => '856',
            'defaultLang' => 'en',
            'nationality' => 'Laotian',
            'currency' => 'USD',
        ],
        'LV' => [
            'iso' => 'LV',
            'name' => 'Latvia',
            'iso3' => 'LVA',
            'prefix' => '371',
            'defaultLang' => 'en',
            'nationality' => 'Latvian',
            'currency' => 'EUR',
        ],
        'LB' => [
            'iso' => 'LB',
            'name' => 'Lebanon',
            'iso3' => 'LBN',
            'prefix' => '961',
            'defaultLang' => 'en',
            'nationality' => 'Lebanese',
            'currency' => 'USD',
        ],
        'LS' => [
            'iso' => 'LS',
            'name' => 'Lesotho',
            'iso3' => 'LSO',
            'prefix' => '266',
            'defaultLang' => 'en',
            'nationality' => 'Mosotho',
            'currency' => 'USD',
        ],
        'LR' => [
            'iso' => 'LR',
            'name' => 'Liberia',
            'iso3' => 'LBR',
            'prefix' => '231',
            'defaultLang' => 'en',
            'nationality' => 'Liberian',
            'currency' => 'USD',
        ],
        'LY' => [
            'iso' => 'LY',
            'name' => 'Libyan Arab Jamahiriya',
            'iso3' => 'LBY',
            'prefix' => '218',
            'defaultLang' => 'ar',
            'nationality' => 'Libyan',
            'currency' => 'USD',
        ],
        'LI' => [
            'iso' => 'LI',
            'name' => 'Liechtenstein',
            'iso3' => 'LIE',
            'prefix' => '423',
            'defaultLang' => 'en',
            'nationality' => 'Liechtensteiner',
            'currency' => 'USD',
        ],
        'LT' => [
            'iso' => 'LT',
            'name' => 'Lithuania',
            'iso3' => 'LTU',
            'prefix' => '370',
            'defaultLang' => 'en',
            'nationality' => 'Lithuanian',
            'currency' => 'EUR',
        ],
        'LU' => [
            'iso' => 'LU',
            'name' => 'Luxembourg',
            'iso3' => 'LUX',
            'prefix' => '352',
            'defaultLang' => 'en',
            'nationality' => 'Luxembourger',
            'currency' => 'EUR',
        ],
        'MO' => [
            'iso' => 'MO',
            'name' => 'Macao',
            'iso3' => 'MAC',
            'prefix' => '853',
            'defaultLang' => 'pt-br',
            'nationality' => 'Macanese',
            'currency' => 'USD',
        ],
        'MK' => [
            'iso' => 'MK',
            'name' => 'Macedonia, the Former Yugoslav Republic of',
            'iso3' => 'MKD',
            'prefix' => '389',
            'defaultLang' => 'en',
            'nationality' => 'Macedonian',
            'currency' => 'USD',
        ],
        'MG' => [
            'iso' => 'MG',
            'name' => 'Madagascar',
            'iso3' => 'MDG',
            'prefix' => '261',
            'defaultLang' => 'fr',
            'nationality' => 'Malagasy',
            'currency' => 'USD',
        ],
        'MW' => [
            'iso' => 'MW',
            'name' => 'Malawi',
            'iso3' => 'MWI',
            'prefix' => '265',
            'defaultLang' => 'en',
            'nationality' => 'Malawian',
            'currency' => 'USD',
        ],
        'MY' => [
            'iso' => 'MY',
            'name' => 'Malaysia',
            'iso3' => 'MYS',
            'prefix' => '60',
            'defaultLang' => 'en',
            'nationality' => 'Malaysian',
            'currency' => 'USD',
        ],
        'MV' => [
            'iso' => 'MV',
            'name' => 'Maldives',
            'iso3' => 'MDV',
            'prefix' => '960',
            'defaultLang' => 'en',
            'nationality' => 'Maldivan',
            'currency' => 'USD',
        ],
        'ML' => [
            'iso' => 'ML',
            'name' => 'Mali',
            'iso3' => 'MLI',
            'prefix' => '223',
            'defaultLang' => 'en',
            'nationality' => 'Malian',
            'currency' => 'USD',
        ],
        'MT' => [
            'iso' => 'MT',
            'name' => 'Malta',
            'iso3' => 'MLT',
            'prefix' => '356',
            'defaultLang' => 'en',
            'nationality' => 'Maltese',
            'currency' => 'EUR',
        ],
        'MH' => [
            'iso' => 'MH',
            'name' => 'Marshall Islands',
            'iso3' => 'MHL',
            'prefix' => '692',
            'defaultLang' => 'en',
            'nationality' => 'Marshallese',
            'currency' => 'USD',
        ],
        'MQ' => [
            'iso' => 'MQ',
            'name' => 'Martinique',
            'iso3' => 'MTQ',
            'prefix' => '596',
            'defaultLang' => 'fr',
            'nationality' => 'Martinique',
            'currency' => 'USD',
        ],
        'MR' => [
            'iso' => 'MR',
            'name' => 'Mauritania',
            'iso3' => 'MRT',
            'prefix' => '222',
            'defaultLang' => 'en',
            'nationality' => 'Mauritanian',
            'currency' => 'USD',
        ],
        'MU' => [
            'iso' => 'MU',
            'name' => 'Mauritius',
            'iso3' => 'MUS',
            'prefix' => '2302',
            'defaultLang' => 'en',
            'nationality' => 'Mauritian',
            'currency' => 'USD',
        ],
        'YT' => [
            'iso' => 'YT',
            'name' => 'Mayotte',
            'iso3' => null,
            'prefix' => '262',
            'defaultLang' => 'en',
            'nationality' => 'Mahoran',
            'currency' => 'USD',
        ],
        'MX' => [
            'iso' => 'MX',
            'name' => 'Mexico',
            'iso3' => 'MEX',
            'prefix' => '52',
            'defaultLang' => 'es',
            'nationality' => 'Mexican',
            'currency' => 'USD',
        ],
        'FM' => [
            'iso' => 'FM',
            'name' => 'Micronesia, Federated States of',
            'iso3' => 'FSM',
            'prefix' => '691',
            'defaultLang' => 'en',
            'nationality' => 'Micronesian',
            'currency' => 'USD',
        ],
        'MD' => [
            'iso' => 'MD',
            'name' => 'Moldova, Republic of',
            'iso3' => 'MDA',
            'prefix' => '373',
            'defaultLang' => 'en',
            'nationality' => 'Moldovan',
            'currency' => 'USD',
        ],
        'MC' => [
            'iso' => 'MC',
            'name' => 'Monaco',
            'iso3' => 'MCO',
            'prefix' => '377',
            'defaultLang' => 'fr',
            'nationality' => 'Monegasque/Monacan',
            'currency' => 'USD',
        ],
        'MN' => [
            'iso' => 'MN',
            'name' => 'Mongolia',
            'iso3' => 'MNG',
            'prefix' => '976',
            'defaultLang' => 'en',
            'nationality' => 'Mongolian',
            'currency' => 'USD',
        ],
        'MS' => [
            'iso' => 'MS',
            'name' => 'Montserrat',
            'iso3' => 'MSR',
            'prefix' => '1664',
            'defaultLang' => 'en',
            'nationality' => 'Montserrat',
            'currency' => 'USD',
        ],
        'MA' => [
            'iso' => 'MA',
            'name' => 'Morocco',
            'iso3' => 'MAR',
            'prefix' => '212',
            'defaultLang' => 'ar',
            'nationality' => 'Moroccan',
            'currency' => 'USD',
        ],
        'MZ' => [
            'iso' => 'MZ',
            'name' => 'Mozambique',
            'iso3' => 'MOZ',
            'prefix' => '258',
            'defaultLang' => 'pt-br',
            'nationality' => 'Mozambican',
            'currency' => 'USD',
        ],
        'MM' => [
            'iso' => 'MM',
            'name' => 'Myanmar',
            'iso3' => 'MMR',
            'prefix' => '95',
            'defaultLang' => 'en',
            'nationality' => 'Myanmarese/Burmese',
            'currency' => 'USD',
        ],
        'NA' => [
            'iso' => 'NA',
            'name' => 'Namibia',
            'iso3' => 'NAM',
            'prefix' => '264',
            'defaultLang' => 'en',
            'nationality' => 'Namibian',
            'currency' => 'USD',
        ],
        'NR' => [
            'iso' => 'NR',
            'name' => 'Nauru',
            'iso3' => 'NRU',
            'prefix' => '674',
            'defaultLang' => 'en',
            'nationality' => 'Nauruan',
            'currency' => 'USD',
        ],
        'NP' => [
            'iso' => 'NP',
            'name' => 'Nepal',
            'iso3' => 'NPL',
            'prefix' => '977',
            'defaultLang' => 'en',
            'nationality' => 'Nepalese',
            'currency' => 'USD',
        ],
        'NL' => [
            'iso' => 'NL',
            'name' => 'Netherlands',
            'iso3' => 'NLD',
            'prefix' => '31',
            'defaultLang' => 'en',
            'nationality' => 'Dutch',
            'currency' => 'EUR',
        ],
        'AN' => [
            'iso' => 'AN',
            'name' => 'Netherlands Antilles',
            'iso3' => 'ANT',
            'prefix' => '599',
            'defaultLang' => 'fr',
            'nationality' => 'Netherlands Antilles',
            'currency' => 'USD',
        ],
        'NC' => [
            'iso' => 'NC',
            'name' => 'New Caledonia',
            'iso3' => 'NCL',
            'prefix' => '687',
            'defaultLang' => 'en',
            'nationality' => 'New Caledonian',
            'currency' => 'USD',
        ],
        'NZ' => [
            'iso' => 'NZ',
            'name' => 'New Zealand',
            'iso3' => 'NZL',
            'prefix' => '64',
            'defaultLang' => 'en',
            'nationality' => 'New Zealander',
            'currency' => 'USD',
        ],
        'NI' => [
            'iso' => 'NI',
            'name' => 'Nicaragua',
            'iso3' => 'NIC',
            'prefix' => '505',
            'defaultLang' => 'es',
            'nationality' => 'Nicaraguan',
            'currency' => 'USD',
        ],
        'NE' => [
            'iso' => 'NE',
            'name' => 'Niger',
            'iso3' => 'NER',
            'prefix' => '227',
            'defaultLang' => 'en',
            'nationality' => 'Nigerien',
            'currency' => 'USD',
        ],
        'NG' => [
            'iso' => 'NG',
            'name' => 'Nigeria',
            'iso3' => 'NGA',
            'prefix' => '234',
            'defaultLang' => 'en',
            'nationality' => 'Nigerian',
            'currency' => 'USD',
        ],
        'NU' => [
            'iso' => 'NU',
            'name' => 'Niue',
            'iso3' => 'NIU',
            'prefix' => '683',
            'defaultLang' => 'en',
            'nationality' => 'Niuean',
            'currency' => 'USD',
        ],
        'NF' => [
            'iso' => 'NF',
            'name' => 'Norfolk Island',
            'iso3' => 'NFK',
            'prefix' => '672',
            'defaultLang' => 'en',
            'nationality' => 'Norfolk Islander',
            'currency' => 'USD',
        ],
        'MP' => [
            'iso' => 'MP',
            'name' => 'Northern Mariana Islands',
            'iso3' => 'MNP',
            'prefix' => '1670',
            'defaultLang' => 'en',
            'nationality' => 'Northern Mariana Islander',
            'currency' => 'USD',
        ],
        'NO' => [
            'iso' => 'NO',
            'name' => 'Norway',
            'iso3' => 'NOR',
            'prefix' => '47',
            'defaultLang' => 'en',
            'nationality' => 'Norwegian',
            'currency' => 'USD',
        ],
        'OM' => [
            'iso' => 'OM',
            'name' => 'Oman',
            'iso3' => 'OMN',
            'prefix' => '968',
            'defaultLang' => 'ar',
            'nationality' => 'Omani',
            'currency' => 'USD',
        ],
        'PK' => [
            'iso' => 'PK',
            'name' => 'Pakistan',
            'iso3' => 'PAK',
            'prefix' => '92',
            'defaultLang' => 'en',
            'nationality' => 'Pakistani',
            'currency' => 'USD',
        ],
        'PW' => [
            'iso' => 'PW',
            'name' => 'Palau',
            'iso3' => 'PLW',
            'prefix' => '680',
            'defaultLang' => 'en',
            'nationality' => 'Palauan',
            'currency' => 'USD',
        ],
        'PS' => [
            'iso' => 'PS',
            'name' => 'Palestinian Territory',
            'iso3' => '',
            'prefix' => '970',
            'defaultLang' => 'ar',
            'nationality' => 'Palestinian Territory',
            'currency' => 'USD',
        ],
        'PA' => [
            'iso' => 'PA',
            'name' => 'Panama',
            'iso3' => 'PAN',
            'prefix' => '507',
            'defaultLang' => 'es',
            'nationality' => 'Panamanian',
            'currency' => 'USD',
        ],
        'PG' => [
            'iso' => 'PG',
            'name' => 'Papua New Guinea',
            'iso3' => 'PNG',
            'prefix' => '675',
            'defaultLang' => 'en',
            'nationality' => 'Papua New Guinean',
            'currency' => 'USD',
        ],
        'PY' => [
            'iso' => 'PY',
            'name' => 'Paraguay',
            'iso3' => 'PRY',
            'prefix' => '595',
            'defaultLang' => 'es',
            'nationality' => 'Paraguayan',
            'currency' => 'USD',
        ],
        'PE' => [
            'iso' => 'PE',
            'name' => 'Peru',
            'iso3' => 'PER',
            'prefix' => '51',
            'defaultLang' => 'es',
            'nationality' => 'Peruvian',
            'currency' => 'USD',
        ],
        'PH' => [
            'iso' => 'PH',
            'name' => 'Philippines',
            'iso3' => 'PHL',
            'prefix' => '63',
            'defaultLang' => 'en',
            'nationality' => 'Filipino',
            'currency' => 'USD',
        ],
        'PN' => [
            'iso' => 'PN',
            'name' => 'Pitcairn',
            'iso3' => 'PCN',
            'prefix' => '870',
            'defaultLang' => 'en',
            'nationality' => 'Pitcairn Islander',
            'currency' => 'USD',
        ],
        'PL' => [
            'iso' => 'PL',
            'name' => 'Poland',
            'iso3' => 'POL',
            'prefix' => '48',
            'defaultLang' => 'en',
            'nationality' => 'Polish',
            'currency' => 'USD',
        ],
        'PT' => [
            'iso' => 'PT',
            'name' => 'Portugal',
            'iso3' => 'PRT',
            'prefix' => '351',
            'defaultLang' => 'pt-br',
            'nationality' => 'Portuguese',
            'currency' => 'EUR',
        ],
        'PR' => [
            'iso' => 'PR',
            'name' => 'Puerto Rico',
            'iso3' => 'PRI',
            'prefix' => '1',
            'defaultLang' => 'es',
            'nationality' => 'Puerto Rican',
            'currency' => 'USD',
        ],
        'QA' => [
            'iso' => 'QA',
            'name' => 'Qatar',
            'iso3' => 'QAT',
            'prefix' => '974',
            'defaultLang' => 'ar',
            'nationality' => 'Qatari',
            'currency' => 'USD',
        ],
        'RE' => [
            'iso' => 'RE',
            'name' => 'Reunion',
            'iso3' => 'REU',
            'prefix' => '',
            'defaultLang' => 'fr',
            'nationality' => 'Reunion',
            'currency' => 'USD',
        ],
        'RO' => [
            'iso' => 'RO',
            'name' => 'Romania',
            'iso3' => 'ROU',
            'prefix' => '40',
            'defaultLang' => 'en',
            'nationality' => 'Romanian',
            'currency' => 'USD',
        ],
        'RU' => [
            'iso' => 'RU',
            'name' => 'Russia',
            'iso3' => 'RUS',
            'prefix' => '7',
            'defaultLang' => 'ru',
            'nationality' => 'Russian',
            'currency' => 'USD',
        ],
        'RW' => [
            'iso' => 'RW',
            'name' => 'Rwanda',
            'iso3' => 'RWA',
            'prefix' => '250',
            'defaultLang' => 'en',
            'nationality' => 'Rwandan',
            'currency' => 'USD',
        ],
        'SH' => [
            'iso' => 'SH',
            'name' => 'Saint Helena',
            'iso3' => 'SHN',
            'prefix' => '290',
            'defaultLang' => 'en',
            'nationality' => 'Saint Helenian',
            'currency' => 'USD',
        ],
        'KN' => [
            'iso' => 'KN',
            'name' => 'Saint Kitts and Nevis',
            'iso3' => 'KNA',
            'prefix' => '1869',
            'defaultLang' => 'en',
            'nationality' => 'Kittian/Nevisian',
            'currency' => 'USD',
        ],
        'LC' => [
            'iso' => 'LC',
            'name' => 'Saint Lucia',
            'iso3' => 'LCA',
            'prefix' => '1758',
            'defaultLang' => 'en',
            'nationality' => 'Saint Lucian',
            'currency' => 'USD',
        ],
        'PM' => [
            'iso' => 'PM',
            'name' => 'Saint Pierre and Miquelon',
            'iso3' => 'SPM',
            'prefix' => '508',
            'defaultLang' => 'en',
            'nationality' => 'Saint-Pierrais/Miquelonnais',
            'currency' => 'USD',
        ],
        'VC' => [
            'iso' => 'VC',
            'name' => 'Saint Vincent and the Grenadines',
            'iso3' => 'VCT',
            'prefix' => '1784',
            'defaultLang' => 'en',
            'nationality' => 'Saint Vincent and the Grenadines',
            'currency' => 'USD',
        ],
        'WS' => [
            'iso' => 'WS',
            'name' => 'Samoa',
            'iso3' => 'WSM',
            'prefix' => '685',
            'defaultLang' => 'en',
            'nationality' => 'Samoan',
            'currency' => 'USD',
        ],
        'SM' => [
            'iso' => 'SM',
            'name' => 'San Marino',
            'iso3' => 'SMR',
            'prefix' => '378',
            'defaultLang' => 'en',
            'nationality' => 'San Marinese',
            'currency' => 'USD',
        ],
        'ST' => [
            'iso' => 'ST',
            'name' => 'Sao Tome and Principe',
            'iso3' => 'STP',
            'prefix' => '239',
            'defaultLang' => 'en',
            'nationality' => 'Sao Tomean',
            'currency' => 'USD',
        ],
        'SA' => [
            'iso' => 'SA',
            'name' => 'Saudi Arabia',
            'iso3' => 'SAU',
            'prefix' => '966',
            'defaultLang' => 'ar',
            'nationality' => 'Saudi',
            'currency' => 'USD',
        ],
        'SN' => [
            'iso' => 'SN',
            'name' => 'Senegal',
            'iso3' => 'SEN',
            'prefix' => '221',
            'defaultLang' => 'en',
            'nationality' => 'Senegalese',
            'currency' => 'USD',
        ],
        'CS' => [
            'iso' => 'CS',
            'name' => 'Serbia',
            'iso3' => '',
            'prefix' => '381',
            'defaultLang' => 'ru',
            'nationality' => 'Serbian',
            'currency' => 'USD',
        ],
        'SC' => [
            'iso' => 'SC',
            'name' => 'Seychelles',
            'iso3' => 'SYC',
            'prefix' => '248',
            'defaultLang' => 'fr',
            'nationality' => 'Seychellois',
            'currency' => 'USD',
        ],
        'SL' => [
            'iso' => 'SL',
            'name' => 'Sierra Leone',
            'iso3' => 'SLE',
            'prefix' => '232',
            'defaultLang' => 'en',
            'nationality' => 'Sierra Leonean',
            'currency' => 'USD',
        ],
        'SG' => [
            'iso' => 'SG',
            'name' => 'Singapore',
            'iso3' => 'SGP',
            'prefix' => '65',
            'defaultLang' => 'en',
            'nationality' => 'Singaporean',
            'currency' => 'USD',
        ],
        'SK' => [
            'iso' => 'SK',
            'name' => 'Slovakia',
            'iso3' => 'SVK',
            'prefix' => '421',
            'defaultLang' => 'en',
            'nationality' => 'Slovakian',
            'currency' => 'EUR',
        ],
        'SI' => [
            'iso' => 'SI',
            'name' => 'Slovenia',
            'iso3' => 'SVN',
            'prefix' => '386',
            'defaultLang' => 'ru',
            'nationality' => 'Slovenian',
            'currency' => 'EUR',
        ],
        'SB' => [
            'iso' => 'SB',
            'name' => 'Solomon Islands',
            'iso3' => 'SLB',
            'prefix' => '677',
            'defaultLang' => 'en',
            'nationality' => 'Solomon Islander',
            'currency' => 'USD',
        ],
        'SO' => [
            'iso' => 'SO',
            'name' => 'Somalia',
            'iso3' => 'SOM',
            'prefix' => '252',
            'defaultLang' => 'en',
            'nationality' => 'Somali',
            'currency' => 'USD',
        ],
        'ZA' => [
            'iso' => 'ZA',
            'name' => 'South Africa',
            'iso3' => 'ZAF',
            'prefix' => '27',
            'defaultLang' => 'en',
            'nationality' => 'South African',
            'currency' => 'USD',
        ],
        'GS' => [
            'iso' => 'GS',
            'name' => 'South Georgia and the South Sandwich Islands',
            'iso3' => null,
            'prefix' => '500',
            'defaultLang' => 'en',
            'nationality' => 'South Georgia and the South Sandwich Islander',
            'currency' => 'USD',
        ],
        'ES' => [
            'iso' => 'ES',
            'name' => 'Spain',
            'iso3' => 'ESP',
            'prefix' => '34',
            'defaultLang' => 'es',
            'nationality' => 'Spanish',
            'currency' => 'EUR',
        ],
        'LK' => [
            'iso' => 'LK',
            'name' => 'Sri Lanka',
            'iso3' => 'LKA',
            'prefix' => '94',
            'defaultLang' => 'en',
            'nationality' => 'Sri Lankan',
            'currency' => 'USD',
        ],
        'SD' => [
            'iso' => 'SD',
            'name' => 'Sudan',
            'iso3' => 'SDN',
            'prefix' => '249',
            'defaultLang' => 'ar',
            'nationality' => 'Sudanese',
            'currency' => 'USD',
        ],
        'SR' => [
            'iso' => 'SR',
            'name' => 'Suriname',
            'iso3' => 'SUR',
            'prefix' => '597',
            'defaultLang' => 'en',
            'nationality' => 'Surinamer',
            'currency' => 'USD',
        ],
        'SJ' => [
            'iso' => 'SJ',
            'name' => 'Svalbard and Jan Mayen',
            'iso3' => 'SJM',
            'prefix' => '47',
            'defaultLang' => 'en',
            'nationality' => 'Svalbard and Jan Mayen',
            'currency' => 'USD',
        ],
        'SZ' => [
            'iso' => 'SZ',
            'name' => 'Swaziland',
            'iso3' => 'SWZ',
            'prefix' => '268',
            'defaultLang' => 'en',
            'nationality' => 'Swazi',
            'currency' => 'USD',
        ],
        'SE' => [
            'iso' => 'SE',
            'name' => 'Sweden',
            'iso3' => 'SWE',
            'prefix' => '46',
            'defaultLang' => 'en',
            'nationality' => 'Swedish',
            'currency' => 'USD',
        ],
        'CH' => [
            'iso' => 'CH',
            'name' => 'Switzerland',
            'iso3' => 'CHE',
            'prefix' => '41',
            'defaultLang' => 'en',
            'nationality' => 'Swiss',
            'currency' => 'USD',
        ],
        'SY' => [
            'iso' => 'SY',
            'name' => 'Syrian Arab Republic',
            'iso3' => 'SYR',
            'prefix' => '963',
            'defaultLang' => 'ar',
            'nationality' => 'Syrian',
            'currency' => 'USD',
        ],
        'TW' => [
            'iso' => 'TW',
            'name' => 'Taiwan, Province of China',
            'iso3' => 'TWN',
            'prefix' => '886',
            'defaultLang' => 'en',
            'nationality' => 'Taiwanese',
            'currency' => 'USD',
        ],
        'TJ' => [
            'iso' => 'TJ',
            'name' => 'Tajikistan',
            'iso3' => 'TJK',
            'prefix' => '992',
            'defaultLang' => 'en',
            'nationality' => 'Tajik',
            'currency' => 'USD',
        ],
        'TZ' => [
            'iso' => 'TZ',
            'name' => 'Tanzania, United Republic of',
            'iso3' => 'TZA',
            'prefix' => '255',
            'defaultLang' => 'en',
            'nationality' => 'Tanzanian',
            'currency' => 'USD',
        ],
        'TH' => [
            'iso' => 'TH',
            'name' => 'Thailand',
            'iso3' => 'THA',
            'prefix' => '66',
            'defaultLang' => 'en',
            'nationality' => 'Thai',
            'currency' => 'USD',
        ],
        'TL' => [
            'iso' => 'TL',
            'name' => 'Timor-Leste',
            'iso3' => null,
            'prefix' => '670',
            'defaultLang' => 'pt-br',
            'nationality' => 'Timorese',
            'currency' => 'USD',
        ],
        'TG' => [
            'iso' => 'TG',
            'name' => 'Togo',
            'iso3' => 'TGO',
            'prefix' => '228',
            'defaultLang' => 'en',
            'nationality' => 'Togolese',
            'currency' => 'USD',
        ],
        'TK' => [
            'iso' => 'TK',
            'name' => 'Tokelau',
            'iso3' => 'TKL',
            'prefix' => '690',
            'defaultLang' => 'en',
            'nationality' => 'Tokelauan',
            'currency' => 'USD',
        ],
        'TO' => [
            'iso' => 'TO',
            'name' => 'Tonga',
            'iso3' => 'TON',
            'prefix' => '676',
            'defaultLang' => 'en',
            'nationality' => 'Tongan',
            'currency' => 'USD',
        ],
        'TT' => [
            'iso' => 'TT',
            'name' => 'Trinidad and Tobago',
            'iso3' => 'TTO',
            'prefix' => '1868',
            'defaultLang' => 'en',
            'nationality' => 'Trinidadian/Tobagonian',
            'currency' => 'USD',
        ],
        'TN' => [
            'iso' => 'TN',
            'name' => 'Tunisia',
            'iso3' => 'TUN',
            'prefix' => '216',
            'defaultLang' => 'ar',
            'nationality' => 'Tunisian',
            'currency' => 'USD',
        ],
        'TR' => [
            'iso' => 'TR',
            'name' => 'Turkey',
            'iso3' => 'TUR',
            'prefix' => '90',
            'defaultLang' => 'en',
            'nationality' => 'Turkish',
            'currency' => 'USD',
        ],
        'TM' => [
            'iso' => 'TM',
            'name' => 'Turkmenistan',
            'iso3' => 'TKM',
            'prefix' => '993',
            'defaultLang' => 'ar',
            'nationality' => 'Turkmen',
            'currency' => 'USD',
        ],
        'TC' => [
            'iso' => 'TC',
            'name' => 'Turks and Caicos Islands',
            'iso3' => 'TCA',
            'prefix' => '1649',
            'defaultLang' => 'en',
            'nationality' => 'Turks and Caicos Islander',
            'currency' => 'USD',
        ],
        'TV' => [
            'iso' => 'TV',
            'name' => 'Tuvalu',
            'iso3' => 'TUV',
            'prefix' => '688',
            'defaultLang' => 'en',
            'nationality' => 'Tuvaluan',
            'currency' => 'USD',
        ],
        'UG' => [
            'iso' => 'UG',
            'name' => 'Uganda',
            'iso3' => 'UGA',
            'prefix' => '256',
            'defaultLang' => 'en',
            'nationality' => 'Ugandan',
            'currency' => 'USD',
        ],
        'UA' => [
            'iso' => 'UA',
            'name' => 'Ukraine',
            'iso3' => 'UKR',
            'prefix' => '380',
            'defaultLang' => 'ru',
            'nationality' => 'Ukrainian',
            'currency' => 'USD',
        ],
        'AE' => [
            'iso' => 'AE',
            'name' => 'United Arab Emirates',
            'iso3' => 'ARE',
            'prefix' => '971',
            'defaultLang' => 'en',
            'nationality' => 'Emirian',
            'currency' => 'USD',
        ],
        'GB' => [
            'iso' => 'GB',
            'name' => 'United Kingdom',
            'iso3' => 'GBR',
            'prefix' => '44',
            'defaultLang' => 'en',
            'nationality' => 'British',
            'currency' => 'GBP',
        ],
        'UK' => [
            'iso' => 'GB',
            'name' => 'United Kingdom',
            'iso3' => 'GBR',
            'prefix' => '44',
            'defaultLang' => 'en',
            'nationality' => 'British',
            'currency' => 'GBP',
        ],
        'US' => [
            'iso' => 'US',
            'name' => 'United States',
            'iso3' => 'USA',
            'prefix' => '1',
            'defaultLang' => 'en',
            'nationality' => 'American',
            'currency' => 'USD',
        ],
        'UM' => [
            'iso' => 'UM',
            'name' => 'United States Minor Outlying Islands',
            'iso3' => '',
            'prefix' => '',
            'defaultLang' => 'en',
            'nationality' => 'American Islander',
            'currency' => 'USD',
        ],
        'UY' => [
            'iso' => 'UY',
            'name' => 'Uruguay',
            'iso3' => 'URY',
            'prefix' => '598',
            'defaultLang' => 'es',
            'nationality' => 'Uruguayan',
            'currency' => 'USD',
        ],
        'UZ' => [
            'iso' => 'UZ',
            'name' => 'Uzbekistan',
            'iso3' => 'UZB',
            'prefix' => '998',
            'defaultLang' => 'ru',
            'nationality' => 'Uzbekistani',
            'currency' => 'USD',
        ],
        'VU' => [
            'iso' => 'VU',
            'name' => 'Vanuatu',
            'iso3' => 'VUT',
            'prefix' => '678',
            'defaultLang' => 'en',
            'nationality' => 'Vanuatuan',
            'currency' => 'USD',
        ],
        'VE' => [
            'iso' => 'VE',
            'name' => 'Venezuela',
            'iso3' => 'VEN',
            'prefix' => '58',
            'defaultLang' => 'es',
            'nationality' => 'Venezuelan',
            'currency' => 'USD',
        ],
        'VN' => [
            'iso' => 'VN',
            'name' => 'Viet Nam',
            'iso3' => 'VNM',
            'prefix' => '84',
            'defaultLang' => 'en',
            'nationality' => 'Vietnamese',
            'currency' => 'USD',
        ],
        'VG' => [
            'iso' => 'VG',
            'name' => 'Virgin Islands, British',
            'iso3' => 'VGB',
            'prefix' => '1284',
            'defaultLang' => 'en',
            'nationality' => 'Virgin Islander ',
            'currency' => 'USD',
        ],
        'VI' => [
            'iso' => 'VI',
            'name' => 'Virgin Islands, U.s.',
            'iso3' => 'VIR',
            'prefix' => '1340',
            'defaultLang' => 'en',
            'nationality' => ' U.S. Virgin Islander',
            'currency' => 'USD',
        ],
        'WF' => [
            'iso' => 'WF',
            'name' => 'Wallis and Futuna',
            'iso3' => 'WLF',
            'prefix' => '681',
            'defaultLang' => 'en',
            'nationality' => 'Wallisian/Futunan',
            'currency' => 'USD',
        ],
        'EH' => [
            'iso' => 'EH',
            'name' => 'Western Sahara',
            'iso3' => 'ESH',
            'prefix' => '212',
            'defaultLang' => 'en',
            'nationality' => 'Western Sahara/Sahrawi',
            'currency' => 'USD',
        ],
        'YE' => [
            'iso' => 'YE',
            'name' => 'Yemen',
            'iso3' => 'YEM',
            'prefix' => '967',
            'defaultLang' => 'en',
            'nationality' => 'Yemeni',
            'currency' => 'USD',
        ],
        'ZM' => [
            'iso' => 'ZM',
            'name' => 'Zambia',
            'iso3' => 'ZMB',
            'prefix' => '260',
            'defaultLang' => 'en',
            'nationality' => 'Zambian',
            'currency' => 'USD',
        ],
        'ZW' => [
            'iso' => 'ZW',
            'name' => 'Zimbabwe',
            'iso3' => 'ZWE',
            'prefix' => '263',
            'defaultLang' => 'en',
            'nationality' => 'Zimbabwean',
            'currency' => 'USD',
        ],
        'ME' => [
            'iso' => 'ME',
            'name' => 'Montenegro',
            'iso3' => 'MNE',
            'prefix' => '382',
            'defaultLang' => 'en',
            'nationality' => 'Montenegrin',
            'currency' => 'USD',
        ],
        'KV' => [
            'iso' => 'KV',
            'name' => 'Kosovo',
            'iso3' => 'UNK',
            'prefix' => '381',
            'defaultLang' => 'ru',
            'nationality' => null,
            'currency' => 'USD',
        ],
        'AX' => [
            'iso' => 'AX',
            'name' => 'Aland Islands',
            'iso3' => 'ALA',
            'prefix' => '358',
            'defaultLang' => 'en',
            'nationality' => 'Finnish',
            'currency' => 'USD',
        ],
    ];

    public static function getCountryName($iso)
    {
        $country = self::getArrayKey($iso, self::$countries);
        $name = self::getArrayKey('name', $country, 'Unknown');
        return __($name);
    }

    public static function getCountriesForValidation($allowAnon = true)
    {
        $keys = array_keys(self::$countries);
        if (true !== $allowAnon) {
            $keys = array_filter($keys, function ($var) {
                return (strtoupper($var) !== 'XX');
            });
        }
        return $keys;
    }

    public static function getCountriesByCountryCode()
    {
        $return = [];
        foreach (self::$countries as $iso => $data) {
            $code = self::getArrayKey('prefix', $data, null);
            if (!is_null($code)) {
                if (!array_key_exists($code, $return)) {
                    $return[$code] = [];
                }
                array_push($return[$code], $iso);
            }
        }
        ksort($return, SORT_NUMERIC);
        return $return;
    }

    protected static function getArrayKey($key, $array, $default = null)
    {
        return (!is_array($array) || !array_key_exists($key, $array)) ? $default: $array[$key];
    }
}
